name: Build and Deploy

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - main

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"

      - name: Install dependencies
        run: npm install

      - name: Build artifact
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: /home/runner/work/jsbuilder-v1/jsbuilder-v1/build
          retention-days: 1

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: /home/runner/work/jsbuilder-v1/jsbuilder-v1/build

      - name: Push to GitGub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: /home/runner/work/jsbuilder-v1/jsbuilder-v1/build