name: Build and Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  check-labels:
    if: ${{ github.event.pull_request.merged }}
    name: Validate labels
    runs-on: ubuntu-latest
    outputs:
      deployToGitHubPages: ${{ steps.labels.outputs.deployToGitHubPages }}
      deployToDockerHub: ${{ steps.labels.outputs.deployToDockerHub }}
      versionType: ${{ steps.labels.outputs.versionType }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for "release" labels
        uses: actions/github-script@v7
        id: labels
        with:
          script: |
            const labels = context.payload.pull_request.labels.map((label) => label.name);
            const deployToGitHubPages = labels.includes('gh-pages');
            const deployToDockerHub = labels.includes('docker');
            
            let versionType = null;
            if (labels.includes('patch')) {
              versionType = 'patch';
            } else if (labels.includes('minor')) {
              versionType = 'minor';
            } else if (labels.includes('major')) {
              versionType = 'major';
            }
            
            core.setOutput('deployToGitHubPages', deployToGitHubPages);
            core.setOutput('deployToDockerHub', deployToDockerHub);
            core.setOutput('versionType', versionType);

  build:
    name: Build Application
    needs: check-labels
    runs-on: ubuntu-latest
    outputs:
      deployToGitHubPages: ${{ needs.check-labels.outputs.deployToGitHubPages }}
      deployToDockerHub: ${{ needs.check-labels.outputs.deployToDockerHub }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"

      - name: Install semver package
        run: npm install semver --no-save

      - name: Determine new version
        id: version
        run: |
          OLD_VERSION=$(jq -r '.version' package.json)
          NEW_VERSION=$(node -e "console.log(require('semver').inc('$OLD_VERSION', '${{ needs.check-labels.outputs.versionType }}'))")
          echo "version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: npm install

      - name: Build artifact
        run: npm run build-gh-pages

      - name: Upload artifact
        if: ${{ needs.check-labels.outputs.deployToGitHubPages == 'true' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: /home/runner/work/jsbuilder-v1/jsbuilder-v1/build
          retention-days: 1

  deployToGitHubPages:
    if: ${{ needs.build.outputs.deployToGitHubPages == 'true' }}
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Push to GitGub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deployToDockerHub:
    if: ${{ needs.build.outputs.deployToDockerHub == 'true' }}
    name: Deploy to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/jsbuilder-v1:${{ needs.build.outputs.version }}
            ${{ secrets.DOCKER_HUB_USER }}/jsbuilder-v1:latest

  updatePackageVersion:
    name: Update Package Version
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"

      - name: Update Package.json with New Version
        run: |
          jq ".version = \"${{ needs.build.outputs.version }}\"" package.json > temp.json && mv temp.json package.json

      - name: Update PackageLock.json with New Version
        run: npm install

      - name: Commit and Push New Version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git add package-lock.json
          git commit -m "chore: bump version to ${{ needs.build.outputs.version }}"
          git push origin main